# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5e1e6b3a9876b65486dce1f1e8d855385cbf8847ad5a907653b77678162d42d1e81ffa5125d699b5e523de2cad1700acf55fe0ab29e98dd74541d7f0ea6e3c65

test:
  secret_key_base: 8a58f89fb5072bae7b5e03b0253e75179f3ed1e6c04ec0f26cb9731f52e9ec6949ec2b4629e04ace75c00cfebb6cee344fca395afe6b3343dbb0c2ab7dd4a8f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
